config/routes.rb
ItGotWeird::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_scope :user do 
    root to: 'static_pages#home'
	get '/signin', to: 'devise/sessions#new'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
	get '/signout', to: 'devise/sessions#destroy'
  end
  resources :pictures

  resources :blogs

  resources :users
  
  resources :sessions

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/crew', to: 'static_pages#crew', via: 'get'
  match '/videos', to: 'static_pages#videos', via: 'get'
  
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def blog
  end

  def about
  end

  def crew
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/blog.html.erb
<h1>StaticPages#blog</h1>
<p>Find me in app/views/static_pages/blog.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<% meta :keywords => %q(It Got Weird, contact) %>
<div id="ContactBack">
<%= render 'layouts/header' %>
  <div id="BlogContainer" class="container" style="height:auto; border:1px solid transparent;
		border-image: url('assets/chalk.png');
		border-image-slice:25;
		border-image-width: 20 20 20 20;
		border-image-outset: 0;
		border-image-repeat: round;
		margin-top: 5%;
		border-radius: 5px;">
   <h1 id="BlogHeader" style="text-align:center;">Contact</h1>
	<div class="row Blog" style="border-image-width: 0 0 0 0; border-radius: 5px; margin-left: 10%; margin-right:10%;">
		<div class="row BlogContent" style="text-align:center;">Randy.Overland@gmail.com</div>

	</div>
	<%= render 'layouts/footer' %>
  </div>
  
</div>

<script>
	$(document).ready(function() {
		$("#ContactBack").height($(window).height());
		$("#ContactBack").hide().fadeOut(400);
		$("#ContactBack").blur().fadeIn(400);
	});
</script>

app/views/static_pages/crew.html.erb
<h1>StaticPages#crew</h1>
<p>Find me in app/views/static_pages/crew.html.erb</p>

app/views/static_pages/home.html.erb
<% meta :keywords => %q(It Got Weird, sketch comedy, comedy) %>

<div class="row" id="hero"  style="display:block;">
	<img data-stellar-ratio="0.6" id="banner" src="/assets/weirdbanner.jpg" style="position:absolute;">
</div>

<div class="row" id="homenav">
	<div class="col-md-4 col-sm-4 col-xs-4 homenavbutton" data-no-turbolink>
	<%= link_to (sanitize '<h1>Blog</h1>'), blogs_path %></div>
	<div class="col-md-4 col-sm-4 col-xs-4 homenavbutton" data-no-turbolink>
	<%= link_to (sanitize '<h1>Videos</h1>'), "https://www.youtube.com/user/ItGotWeirdComedy" %></div>
	<div class="col-md-4 col-sm-4 col-xs-4 homenavbutton" data-no-turbolink>
	<%= link_to (sanitize '<h1>Contact</h1>'), contact_path %></div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12 parallax" id="main" style="min-height: 320px;" data-stellar-background-ratio="0.6">
	<div class="col-md-5 col-sm-5 col-xs-12" id="trailerheader">
		<h2>The Trailer</h1>
		<iframe id="weirdtrailer" src="//www.youtube.com/embed/o9m4Fy52Uwc?rel=0;3&amp;autohide=1&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
	</div>
		<div class="col-md-6 col-sm-6 col-xs-12" id="slogan" data-stellar-ratio="0.9" data-stellar-vertical-offset="-100" >
		  <div class="title" id="title" data-stellar-ratio="0.70" data-stellar-vertical-offset="-10"><img src="/assets/Title.png"></div>
			 <h2 id="deschead">A Weird Sketch Comedy Series.</h2>
			  <p id="description">
			  <a href="https://www.facebook.com/ItGotWeird"><img src="assets/FB-f-Logo__blue_50.png"></a>
			  <a href="https://twitter.com/ItGotWeird_1"><img src="assets/Twitter_logo_blue.png"></a>
			  </p>
		</div>
		
</div>

<div class="col-md-12 col-sm-12 col-xs-12 parallax" id="cast">
	<h1>Starring</h1>
	  
	  <div class="col-md-3 col-sm-3 col-xs-6 pic">
		<h2>Kevin Anderson</h2>
		<img src="assets/anderson.png">
	  </div>
	  
	  
	  <div class="col-md-3 col-sm-3 col-xs-6 pic">
		<h2>Alexandra Hensley</h2>
		<img src="assets/hensley.png">
	  </div>
	  
	  <div class="col-md-3 col-sm-3 col-xs-6 pic">
		<h2>Zach Pizza</h2>
		<img src="assets/pizza.png">
	  </div>
	  
	  <div class="col-md-3 col-sm-3 col-xs-6 pic">
		<h2>Deirdre Scott</h2>
		<img src="assets/scott.png">
	  </div>
</div>
<div class="col-md-12 col-sm-12 col-xs-12 parallax" id="crew">
	<h1 style="text-align: center;">Created By</h1>
	  
	  <div class="col-md-6 col-sm-6 col-xs-6 pic">
		<h2>Randy Overland</h2>
		<img src="assets/randy.png">
	  </div>
	  
	  <div class="col-md-6 col-sm-6 col-xs-6  pic">
		<h2>Ray Wongchinda</h2>
		<img src="assets/ray.png">
	  </div>
	  
	  <%= render 'layouts/footer' %>
</div>